# OTP Authentication Service Production Configuration

server:
  host: "0.0.0.0"
  port: 8080
  mode: "release"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

database:
  host: "${DB_HOST}"
  port: 5432
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  dbname: "${DB_NAME}"
  sslmode: "require"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: "5m"
  conn_max_idle_time: "5m"

redis:
  addr: "${REDIS_ADDR}"
  password: "${REDIS_PASSWORD}"
  db: 0
  pool_size: 20
  min_idle_conns: 5
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  idle_timeout: "5m"

jwt:
  private_key_pem: "${JWT_PRIVATE_KEY}"
  public_key_pem: "${JWT_PUBLIC_KEY}"
  access_token_ttl: "1h"
  refresh_token_ttl: "168h" # 7 days
  issuer: "otp-auth-service"

otp:
  length: 6
  ttl: "5m"
  sender_type: "sms" # Use real SMS service in production

hash:
  cost: 12 # Higher cost for production

logging:
  level: "info"
  format: "json"
  output: "file"
  file_path: "/var/log/otp-auth/app.log"
  max_size: 100 # MB
  max_backups: 10
  max_age: 30 # days
  compress: true

cors:
  allow_origins:
    - "https://yourdomain.com"
    - "https://app.yourdomain.com"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"
  expose_headers:
    - "X-RateLimit-Limit"
    - "X-RateLimit-Remaining"
    - "X-RateLimit-Reset"
  allow_credentials: true
  max_age: "12h"

security:
  rate_limit:
    enabled: true
    requests: 1000 # Higher limit for production
    window: "1m"
    otp_limit: 3 # Stricter OTP limit
    otp_window: "10m"