# OTP Authentication Service Configuration

server:
  host: "0.0.0.0"
  port: 8080
  mode: "debug" # debug, release, test
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "otp_auth"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  conn_max_idle_time: "5m"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 2
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  idle_timeout: "5m"

jwt:
  # Leave empty to auto-generate keys
  private_key_pem: ""
  public_key_pem: ""
  access_token_ttl: "1h"
  refresh_token_ttl: "168h" # 7 days
  issuer: "otp-auth-service"

otp:
  length: 6
  ttl: "2m"
  sender_type: "console" # console, sms

hash:
  cost: 10 # bcrypt cost (4-31)

logging:
  level: "info" # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, stderr, file
  file_path: "logs/app.log"
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days
  compress: true

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
    - "X-Requested-With"
  expose_headers:
    - "X-RateLimit-Limit"
    - "X-RateLimit-Remaining"
    - "X-RateLimit-Reset"
  allow_credentials: true
  max_age: "12h"

security:
  rate_limit:
    enabled: true
    requests: 100 # requests per window
    window: "1m"
    otp_limit: 3 # OTP requests per window
    otp_window: "10m"